name: CI
on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - uses: actions-rs/cargo@v1
        name: cargo check
        with:
          command: check
          args: --all-features
      - uses: actions-rs/cargo@v1
        name: cargo test
        with:
          command: test
          args: --all-features
      - uses: actions-rs/clippy-check@v1
        name: cargo clippy
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
  create_release:
    name: Create Release
    needs: [test]
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          body: >
            Download the binaries for Release ${{ github.ref }} below for your platform,
            or use the provided shell script for installation
          draft: false
          prerelease: false
  build:
    name: Build
    needs: [test, create_release]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install cargo-wix
        if: matrix.os == 'windows-latest'
        run: cargo install cargo-wix
      - uses: actions-rs/cargo@v1
        name: cargo build
        with:
          command: build
          args: --release --all-features
      - name: Get platform specific asset name
        id: asset_name
        shell: bash
        run: |
          set -ex

          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            echo "::set-output name=name::x86_64-windows-dnd.exe"
            echo "::set-output name=bin::dnd.exe"
          elif [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            echo "::set-output name=name::x86_64-linux-dnd"
            echo "::set-output name=bin::dnd"
          else
            echo "::set-output name=name::x86_64-macos-dnd"
            echo "::set-output name=bin::dnd"
          fi
      - name: Upload Prebuilt Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.url }}
          asset_path: ./target/release/${{ steps.asset_name.outputs.bin }}
          asset_name: ${{ steps.asset_name.outputs.name }}
          asset_content_type: application/octet-stream
      - name: Build Windows Installer
        if: matrix.os == 'windows-latest'
        run: cargo wix
      - name: Upload Windows Installer
        if: matrix.os == 'windows-latest'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.url }}
          asset_path: ./target/wix/dnd-0.1.0-x86_64.msi
          asset_name: x86_64-windows-dnd-installer.msi
          asset_content_type: application/octet-stream
